name: Fetch F1 News
on:
  schedule:
    - cron: '0 */2 * * *' # Checks for news every 2 hours
  workflow_dispatch: # Allows you to test it manually

jobs:
  feed2discord:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and Post F1 News
        uses: tgagor/crosspost-action@v1.6.6
        with:
          # Your Discord Webhook from your GitHub Secrets
          discord-url: ${{ secrets.DISCORD_WEBHOOK }}
          
          # Free F1 News Feed
          rss-url: 'https://motorsport.com'
          
          # Only post articles published in the last 2 hours to avoid spamming
          since: '2'
          since-unit: 'hour'
